### ISSUE TITLE
camera pose estimation module

### ISSUE THREAD

**Issue by Yxs-160** [cs674/pytorch-DISN#2]
Remember me? The person who sent you an email just now, I want to know how you implemented the camera pose estimation module in this repository. I have been looking for this module for a long time. I would be very grateful if you could help me.

**Comment by heeh** [comment]
Hi @Yxs-160, thanks for bring this up. 
I don't think we implemented the camera pose estimation network. 
@eschneeweiss @chuang1990, could you confirm this?

**Comment by Yxs-160** [comment]
Hi@heeh, well If the camera pose estimation network is not implemented, what is the local feature obtained? Given a 3D point, how to obtain the image sampling point if there is no camera matrix, I don't understand.

**Comment by eschneeweiss** [comment]
during training we are handed a transformation matrix, that transforms the 3d points into 2d image points. This was a school project and under the time pressure we skipped the camera pose estimator.
